{
 "title": "lvv-service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }, "content": "# API" },
  {
   "title": "Create Availability",
   "type": "graph",
   "description": "Create API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.createProject.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.createProject.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.createProject.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "Get Availability",
   "type": "graph",
   "description": "Get API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.getProject.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.getProject.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.getProject.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "Update Availability",
   "type": "graph",
   "description": "Update API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.updateProject.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.updateProject.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.updateProject.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "Delete Availability",
   "type": "graph",
   "description": "Delete API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.deleteProject.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.deleteProject.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.deleteProject.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "List Availability",
   "type": "graph",
   "description": "List API response code rates",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "2XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.listProjects.ResponseOut.StatusFamily.2XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "4XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.listProjects.ResponseOut.StatusFamily.4XX.Count",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "sum",
     "alias": "5XX",
     "fleet": "lvv-service-api",
     "granularity": "300",
     "host": "_all",
     "metric": "ProjectResource.listProjects.ResponseOut.StatusFamily.5XX.Count",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Create Latency",
     "fleet": "lvv-service-api",
     "granularity": "60",
     "host": "_all",
     "metric": "ProjectResource.createProject.Time",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Get Latency",
     "fleet": "lvv-service-api",
     "granularity": "60",
     "host": "_all",
     "metric": "ProjectResource.getProject.Time",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Update Latency",
     "fleet": "lvv-service-api",
     "granularity": "60",
     "host": "_all",
     "metric": "ProjectResource.updateProject.Time",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "Delete Latency",
     "fleet": "lvv-service-api",
     "granularity": "60",
     "host": "_all",
     "metric": "ProjectResource.deleteProject.Time",
     "project": "lvv-service"
    },
    {
     "ad": "_all",
     "aggregation": "p99",
     "alias": "List Latency",
     "fleet": "lvv-service-api",
     "granularity": "60",
     "host": "_all",
     "metric": "ProjectResource.listProjects.Time",
     "project": "lvv-service"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 }, "content": "# Canary" },
  {
   "title": "CreateProject Success Rate",
   "type": "graph",
   "description": "Records success of CreateProject canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-service-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-service-canary.createProjectCall",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "GetProjectCompartment Success Rate",
   "type": "graph",
   "description": "Records success of GetProjectCompartment canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-service-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-service-canary.getProjectCall",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "UpdateProject Success Rate",
   "type": "graph",
   "description": "Records success of UpdateProject canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-service-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-service-canary.updateProjectCall",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "ListProject Success Rate",
   "type": "graph",
   "description": "Records success of ListProject canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-service-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-service-canary.listProjectCall",
     "project": "lvv-service"
    }
   ]
  },
  {
   "title": "DeleteProject Success Rate",
   "type": "graph",
   "description": "Records success of DeleteProject canary operation",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "ad": "_all",
     "aggregation": "mean",
     "alias": "Success",
     "fleet": "lvv-service-canary",
     "granularity": "60",
     "host": "_all",
     "metric": "lvv-service-canary.deleteProjectCall",
     "project": "lvv-service"
    }
   ]
  }
 ]
}