<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.oracle.pic.networking.lvv.service</groupId>
        <artifactId>lvv-service-reactor-pom</artifactId>
        <version>0.1-SNAPSHOT</version>
    </parent>

  <artifactId>lvv-service-canary</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>lvv-service-canary</name>

  <properties>
    <jar.main.class>com.oracle.pic.networking.lvv.service.canary.LvvServiceCanary</jar.main.class>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.oracle.oci.sdk</groupId>
      <artifactId>oci-java-sdk-common</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>core-regions</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>service-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>metrics</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.telemetry.overlay.metrics</groupId>
      <artifactId>metrics-module</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.telemetry.commons</groupId>
      <artifactId>metrics-lib</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-lifecycle</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-healthchecks</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.vault</groupId>
      <artifactId>vault-java-sdk</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.vault</groupId>
      <artifactId>vault-user-java-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.networking.lvv.service</groupId>
      <artifactId>lvv-service-java-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>s2s-core-util</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.prism.agent</groupId>
      <artifactId>prism-agent</artifactId>
    </dependency>
  </dependencies>


  <build>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <!-- Copies (does not filter) config resources from config to target/config -->
          <execution>
            <id>copy-config-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/config</outputDirectory>
              <resources>
                <resource>
                  <directory>config</directory>
                  <includes>
                    <include>*.conf</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-scripts-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/scripts</outputDirectory>
              <resources>
                <resource>
                  <directory>scripts</directory>
                  <includes>
                    <include>*</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-docker-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/docker</outputDirectory>
              <resources>
                <resource>
                  <directory>docker</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-environment-config-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/environment-config</outputDirectory>
              <resources>
                <resource>
                  <directory>environment-config</directory>
                  <includes>
                    <include>*.env</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.oracle.pic.commons.maven</groupId>
        <artifactId>oracle-typesafe-config-validator-plugin</artifactId>
        <version>2.0.16</version>
        <executions>
          <execution>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <configsSet>
                <directory>${basedir}/config</directory>
              </configsSet>
              <resolvedConfigDirectory>${project.build.directory}/resolved-config</resolvedConfigDirectory>
              <unresolvedSubstitutions>
                <unresolvedSubstitution>env.availabilityDomain</unresolvedSubstitution>
                <unresolvedSubstitution>env.region</unresolvedSubstitution>
                <unresolvedSubstitution>env.adNumber</unresolvedSubstitution>
                <unresolvedSubstitution>env.regionInternalName</unresolvedSubstitution>
                <unresolvedSubstitution>env.dbTnsName</unresolvedSubstitution>
                <unresolvedSubstitution>env.publicDomainName</unresolvedSubstitution>
                <unresolvedSubstitution>env.iaasDomainName</unresolvedSubstitution>
              </unresolvedSubstitutions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Java code coverage -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.10</version>
        <executions>
          <execution>
            <id>default-prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>default-report</id>
            <goals>
              <goal>report</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/jacoco-reports</outputDirectory>
              <excludes>
                <!-- ignore Canaries for testing, TODO: Fix after LA -->
                <exclude>com/oracle/pic/networking/lvv/service/canary/*</exclude>
                <!-- ignore Canaries for testing, TODO: Fix after LA -->
                <exclude>com/oracle/pic/networking/lvv/service/canary/**/*</exclude>
              </excludes>
            </configuration>
          </execution>
          <execution>
            <id>default-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule implementation="org.jacoco.maven.RuleConfiguration">
                  <element>BUNDLE</element>
                  <limits>
                    <limit implementation="org.jacoco.report.check.Limit">
                      <counter>COMPLEXITY</counter>
                      <value>COVEREDRATIO</value>
                      <!-- Tweak this as you gain coverage, TODO: Fix after LA to 0.8 -->
                      <minimum>0.0</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- maven-dependency-plugin & maven-shade-plugin:
           When instantiating a JCE provider's implementation (class) of a Cipher, KeyAgreement, KeyGenerator, MAC or
           SecretKey factory, the JCA framework determines the provider's codebase (JAR file) and verifies its signature.
           In this way, the JCA authenticates the provider and ensures that only providers signed by a trusted entity
           can be plugged into the JCA. Consequently, these classes cannot be extracted from their original JARs,
           such as the jipher-jce and bc-fips JARs, and included in an application's Uber JAR.
           Instead the original signed JARs must be available to the classloader by placing them in the classpath
           There are corresonding actions in the dockerfile to embed the signed JARs in the docker image. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.oracle.pic.jipher</groupId>
                  <artifactId>jipher-jce</artifactId>
                  <version>${jipher-jce-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>bc-fips</groupId>
                  <artifactId>bc-fips</artifactId>
                  <version>${bouncycastle-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>bcpkix-fips</groupId>
                  <artifactId>bcpkix-fips</artifactId>
                  <version>${bouncycastle-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>com.oracle.pic.prism.agent</groupId>
                  <artifactId>prism-agent</artifactId>
                  <outputDirectory>${project.build.directory}/agentpath</outputDirectory>
                </artifactItem>
              </artifactItems>
              <stripVersion>true</stripVersion>
            </configuration>
          </execution>
          <execution>
            <id>analyze-dependencies</id>
            <configuration>
              <usedDependencies>
                <!-- Used at build time for maven-surefire-plugin to have a Test Engine. -->
                <dependency>org.junit.jupiter:junit-jupiter-engine</dependency>

                <!-- Used at runtime by the Overlay Metrics Module initialization -->
                <dependency>commons-lang:commons-lang</dependency>

                <!-- Used at runtime by the Prism JCE metrics library.
                     The prism-agent is a Java agent. Agents are not included in the application (Uber) jar. It will be
                     provided at runtime by passing '-javaagent:/path/to/prism-agent.jar' to the java command line -->
                <dependency>com.oracle.pic.prism.agent:prism-agent</dependency>
              </usedDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <configuration>
          <!-- We shouldn't need the Dependency Reduced Pom.  Don't change it. -->
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
                <exclude>org/bouncycastle</exclude>
                <exclude>org/bouncycastle/**/*</exclude>
              </excludes>
            </filter>
          </filters>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <manifestEntries>
                    <Main-Class>${jar.main.class}</Main-Class>
                    <Class-Path>classpath/jipher-jce.jar classpath/bc-fips.jar classpath/bcpkix-fips.jar</Class-Path>
                  </manifestEntries>
                </transformer>
              </transformers>
              <artifactSet>
                <excludes>
                  <exclude>com.oracle.pic.prism.agent:prism-agent</exclude>
                  <exclude>com.oracle.pic.jipher:jipher-jce</exclude>
                  <exclude>bc-fips:bc-fips</exclude>
                  <exclude>bcpkix-fips:bcpkix-fips</exclude>
                  <exclude>org.bouncycastle:bcprov-jdk15on</exclude>
                  <exclude>org.bouncycastle:bcpkix-jdk15on</exclude>
                </excludes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
