<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.oracle.pic.networking.lvv.service</groupId>
    <artifactId>lvv-service-reactor-pom</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <artifactId>lvv-service-spec</artifactId>
  <packaging>jar</packaging>
  <version>0.1-SNAPSHOT</version>

  <name>lvv-service-spec</name>

  <properties>
    <!-- The directory with the Swagger spec.-->
    <spec-dir>${project.basedir}/src/specs</spec-dir>

    <!-- The directory containing your enabled groups files. -->
    <enabled-groups-dir>${project.basedir}/src/enabled-conditional-groups</enabled-groups-dir>

    <!-- The Swagger spec file name in the ${spec-dir} directory. -->
    <spec-file-name>api.cond.yaml</spec-file-name>

    <!--
         The preprocessor removes the '.cond' from the above file name, so this is the file name
         that the validator will actually use as input.
    -->
    <preprocessed-spec-file-name>api.yaml</preprocessed-spec-file-name>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>com.oracle.oci.sdk.utilities</groupId>
        <artifactId>spec-conditionals-preprocessor-plugin</artifactId>
        <executions>
          <!-- If you have multiple spec files that need to be preprocessed, run additional executions here. -->
          <execution>
            <id>spec-conditionals-preprocess</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>preprocess</goal>
            </goals>
            <configuration>
              <!--The spec file that should be preprocessed. -->
              <inputFile>${spec-dir}/${spec-file-name}</inputFile>
              <!--
                    The directory containing the enabled group files.
                    In this example, it contains the files internal.txt and release.txt.

                    Having multiple enabled group files allows you to specify different enabled groups at different stages of your
                    service, e.g. have experimental features enabled in a test environment, but only released features in production.

                    Note: Just because you have a 'release.txt' file in this directory will not cause features enabled in it
                    to appear in the public OCI SDKs.
                    For that, see https://confluence.oci.oraclecorp.com/display/DEX/Self-Service+Testing+and+Development
              -->
              <groupFileDir>${enabled-groups-dir}</groupFileDir>
              <!--
                    The output directory for preprocessed files.
                    Since the input spec file name is api.yaml
                    and there are two enabled group files, internal.txt and release.txt, the
                    following files will be created:

                    ${project.build.outputDirectory}/internal/api.yaml
                    ${project.build.outputDirectory}/release/api.yaml
                    (The .cond.yaml extension is changed to .yaml by the preprocessor.)
              -->
              <outputDir>${project.build.outputDirectory}</outputDir>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.2</version>
        <executions>
          <!-- Include the original spec directory. -->
          <execution>
            <id>copy-resources-original</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.outputDirectory}/source</outputDirectory>
              <resources>
                <resource>
                  <directory>${spec-dir}</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
          <!-- Include the enabled group files. -->
          <execution>
            <id>copy-resources-enabled-group-files</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.outputDirectory}/enabled-conditional-groups</outputDirectory>
              <resources>
                <resource>
                  <directory>${enabled-groups-dir}</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.oracle.bmc.sdk</groupId>
        <artifactId>bmc-sdk-swagger-validator</artifactId>
        <executions>
          <!-- It is a good idea to run the spec validator on ALL of the group files. Here, it's internal.txt and release.txt. -->
          <execution>
            <id>public-api-validation</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <!-- Use conditional spec -->
              <specConditionalsInputFile>${spec-dir}/${spec-file-name}</specConditionalsInputFile>
              <specConditionalsGroupFile>${enabled-groups-dir}/internal.txt</specConditionalsGroupFile>
              <configPath>${project.basedir}/spec-validation-config.yaml</configPath>
              <outputPath>${project.basedir}/spec-validation-output.txt</outputPath>
              <failBuildOnError>true</failBuildOnError>
              <treatWarningsAsErrors>true</treatWarningsAsErrors>
            </configuration>
          </execution>
          <execution>
            <id>public-api-validation-release</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <!-- Use conditional spec -->
              <specConditionalsInputFile>${spec-dir}/${spec-file-name}</specConditionalsInputFile>
              <specConditionalsGroupFile>${enabled-groups-dir}/release.txt</specConditionalsGroupFile>
              <configPath>${project.basedir}/spec-validation-config-release.yaml</configPath>
              <outputPath>${project.basedir}/spec-validation-output-release.txt</outputPath>
              <failBuildOnError>true</failBuildOnError>
              <treatWarningsAsErrors>true</treatWarningsAsErrors>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <!-- This will run a script that reverts the spec validator output if the spec and config haven't changed -->
        <artifactId>exec-maven-plugin</artifactId>
        <groupId>org.codehaus.mojo</groupId>
        <version>1.6.0</version>
        <executions>
          <execution>
            <id>Revert spec validation</id>
            <phase>install</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>sh</executable>
              <arguments>
                <argument>
                  possible-revert.sh
                </argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
