include "dev"

logdir: ./abandoned/logs

locationOverride {
     region: "dev"
     availabilityDomain: "dev-1"
}

server {
  requestLog {
    appenders: [{
      type: console
      timeZone: UTC
      threshold: ALL
      target: stdout
      # Default pattern found at:
      # https://github.com/dropwizard/dropwizard/blob/master/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/LogbackAccessRequestLayout.java
      logFormat: "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z,UTC}] \"%responseHeader{opc-request-id}\" \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D"
    }]
  }
}

logging {
  appenders += {
      type: console
      timeZone: UTC
      threshold: DEBUG
      target: stdout
      logFormat: "%-5level %date{ISO8601, UTC} %mdc{opc-request-id} [%thread] %logger: %message%n"
    }
}

metricsConfig {
    locationOverride {
        availabilityDomain=DEV_1
        region=DEV
    }
    t2Config: null
    #t2Config {
        # to test telemetry locally, run: ssh -L 17000:172.18.0.123:17000 bastion.r0.grungy.us
        #endpointOverride: "http://localhost:17000/v1"
    #}
}

authConfig {
  authorizationEnabled: false
  tenantId: ocid1.tenancy.oc1..aaaaaaaa6gqokctiy6pncv6jooomauqibkkhduaohvikdrwi6ze2n5o5v3kq
  authServiceEndpoint: "https://auth.us-r1-1.oraclecloud.com"
  instancePrincipalUrl: "http://localhost:8000/opc/v1/"
  defaultTrustStorePath: "test-data/oci-pki/dev-ca-bundle.pem"
}

ncpServiceConfiguration: {
  endpoint: "https://netops-api.r1.oci.oracleiaas.com"
  connectTimeoutInMs: 5000
  readTimeoutInMs: 5000
}

ideClientConfig: {
  endpoint: "http://localhost:21000"
}