include "base"

stage: DEVELOPMENT

adMappingDisabled: true

assets: {
  mappings: {
    # Should only enable swagger debugging page in test environment.
    "/ui": "/ui",
    "/spec": "/spec"
  }
}

jiraSDConfig {
  jiraSDEndpoint: "https://jira-sd.mc1.oracleiaas.com/"
  usernameSecretPath: "./src/main/resources/jira-sd-test-username"
  passwordSecretPath: "./src/main/resources/jira-sd-test-password"
}

ncpServiceConfiguration: {
  endpoint: "https://netops-api."${env.iaasDomainName}
  connectTimeoutInMs: 5000
  readTimeoutInMs: 5000
}