include "base"

stage: DEVELOPMENT

adMappingDisabled: true

assets: {
  mappings: {
    # Should only enable swagger debugging page in test environment.
    "/ui": "/ui",
    "/spec": "/spec"
  }
}

jiraSDConfig {
  jiraSDEndpoint: "https://jira-sd.mc1.oracleiaas.com/"
  usernameSecretPath: "./src/main/resources/jira-sd-test-username"
  passwordSecretPath: "./src/main/resources/jira-sd-test-password"
}

adDnsName: ad1
regionDnsName: sea

ncpServiceConfiguration: {
  endpoint: "https://ncp-api.svc."${adDnsName}"."${regionDnsName}
  connectTimeoutInMs: 5000
  readTimeoutInMs: 5000
}

identityConfig: {
    authorizationEndpoint: "http://10.145.142.139/"
    enabled: false
    serviceTenantOcid: "ocid1.tenancy.oc1..aaaaaaaagkbzgg6lpzrf47xzy4rjoxg4de6ncfiq2rncmjiujvy2hjgxvziq"
    targetServiceNames: ["oci_c3"]
}