include "base"

stage: PRODUCTION

server {
  minThreads: 1
  maxThreads: 1024
  # The maximum time to wait for Jetty, and all Managed instances, to cleanly shutdown before forcibly terminating them
  shutdownGracePeriod: 30 seconds
  adminMinThreads: 1
  adminMaxThreads: 110 # Should be > 1.5 times the number of cores: https://github.com/dropwizard/dropwizard/issues/523
  applicationConnectors: [{
    type: dynamic-https-with-provider
    port: 8443
    trustPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    #certPath: /secret/lvv-service-api/tls/cert/latest
    #keyPath: /secret/lvv-service-api/key/latest
    #intermediatePath: /secret/lvv-service-api/intermediate/latest # optional
    pkiCertificatePath: /secret/lvv-service-prod/lvv_tls_server_secret/latest
    sslAutoReloadPeriod: 60 minutes
    wantClientAuth: false
    fipsApprovedOnlyMode: true
  }]
  adminConnectors: [{
    type: http,
    port: 21001,
    useForwardedHeaders: false
  }]
  requestLog {
    appenders: [{
      type: file
      currentLogFilename: ${logdir}/requests.log
      archive: true
      archivedLogFilenamePattern: ${logdir}/requests.%d"{yyyy-MM-dd_HH, UTC}".%i.log.gz
      archivedFileCount: 500
      timeZone: UTC
      maxFileSize: 2MB
      totalSizeCap: 10MB
      # Default pattern found at:
      # https://github.com/dropwizard/dropwizard/blob/master/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/LogbackAccessRequestLayout.java
      logFormat: "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z,UTC}] \"%responseHeader{opc-request-id}\" \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D"
    }]
  }
}

metricsConfig {
  t2Config: {
    # For overlay we use the following endpoint
    endpointOverride: "https://telemetry-ingestion."${env.publicDomainName}
  }
}

authConfig: {
  authorizationEnabled: false
  authServiceEndpoint: "https://auth."${env.publicDomainName}
  defaultTrustStorePath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
}

secretServiceConfig: {
  endpoint: "https://secret-service-ce."${env.iaasDomainName}"/v1"
  tlsConfig: {
    caBundle: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  }
}

jiraSDConfig {
  jiraSDEndpoint: "https://jira-sd.mc1.oracleiaas.com/"
  usernameSecretPath: "/secret/lvv-service/jira-sd/username"
  passwordSecretPath: "/secret/lvv-service/jira-sd/password"
}

ncpServiceConfiguration: {
  endpoint: "https:///netops-api."${env.iaasDomainName}
  connectTimeoutInMs: 5000
  readTimeoutInMs: 5000
}

kaasStoreConfig: {
  storeName: ${?KIEV_STORE_NAME}
  appName: "lvv-service"
  compartmentId: "ocid1.compartment.oc1..aaaaaaaah5zjoyuwkiwioc5x2eg6z3x2acnflwcsgkskxojlvc47xrrnlwza"
  tenantId: "ocid1.tenancy.oc1..aaaaaaaaywhaamy7roi5jggknnfrucxsbshmvrtv23nfurmtghsgomi3afhq"
  authEndpoint: "https://auth."${env.publicDomainName}
  frontendEndpoint: "https://"${?KAAS_FRONTEND_ENDPOINT}
  rootCertPemPath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  clientType: service
}
