include "base"

stage: PRODUCTION

adMappingDisabled: true

metricsConfig {
  t2Config: {
    # For overlay we use the following endpoint
    endpointOverride: "https://telemetry-ingestion."${env.publicDomainName}
  }
}

authConfig: {
  authorizationEnabled: true
  authServiceEndpoint: "https://auth."${env.publicDomainName}
  defaultTrustStorePath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
}

secretServiceConfig: {
  endpoint: "https://secret-service-ce."${env.iaasDomainName}"/v1"
}

jiraSDConfig {
  jiraSDEndpoint: "https://jira-sd.mc1.oracleiaas.com/"
  usernameSecretPath: "/secret/lvv-service/jira-sd/username"
  passwordSecretPath: "/secret/lvv-service/jira-sd/password"
}

adDnsName: ad1
regionDnsName: r1

ncpServiceConfiguration: {
  endpoint: "https:///netops-api."${env.iaasDomainName}
  connectTimeoutInMs: 5000
  readTimeoutInMs: 5000
}
