include "base"

stage: PRODUCTION

adMappingDisabled: true

metricsConfig {
  t2Config: {
    # For overlay we use the following endpoint
    endpointOverride: "https://telemetry-ingestion."${env.publicDomainName}
  }
}

authConfig: {
  authorizationEnabled: true
  authServiceEndpoint: "https://auth."${env.publicDomainName}
  defaultTrustStorePath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
}

secretServiceConfig: {
  endpoint: "https://secret-service-ce."${env.iaasDomainName}"/v1"
}
