include "dev.conf"

stage: PRODUCTION

server {
  minThreads: 1
  maxThreads: 1024
  # The maximum time to wait for Jetty, and all Managed instances, to cleanly shutdown before forcibly terminating them
  shutdownGracePeriod: 30 seconds
  adminMinThreads: 1
  adminMaxThreads: 110 # Should be > 1.5 times the number of cores: https://github.com/dropwizard/dropwizard/issues/523
  applicationConnectors: [{
    type: dynamic-https-with-provider
    port: 8443
    trustPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
    #certPath: /secret/lvv-service-api/tls/cert/latest
    #keyPath: /secret/lvv-service-api/key/latest
    #intermediatePath: /secret/lvv-service-api/intermediate/latest # optional
    pkiCertificatePath: /secret/lvv-service-beta/lvv_tls_server_secret/latest
    sslAutoReloadPeriod: 60 minutes
    wantClientAuth: false
    fipsApprovedOnlyMode: true
  }]
  adminConnectors: [{
    type: http,
    port: 21001,
    useForwardedHeaders: false
  }]
  requestLog {
    appenders: [{
      type: file
      currentLogFilename: ${logdir}/requests.log
      archive: true
      archivedLogFilenamePattern: ${logdir}/requests.%d"{yyyy-MM-dd_HH, UTC}".%i.log.gz
      archivedFileCount: 500
      timeZone: UTC
      maxFileSize: 2MB
      totalSizeCap: 10MB
      # Default pattern found at:
      # https://github.com/dropwizard/dropwizard/blob/master/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/LogbackAccessRequestLayout.java
      logFormat: "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z,UTC}] \"%responseHeader{opc-request-id}\" \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D"
    }]
  }
}

kaasStoreConfig: {
  storeName: "lvv_kiev_r2"
  appName: "lvv-service-dev"
  compartmentId: "ocid1.compartment.oc1..aaaaaaaacgjij2knzf3uei7kjel4zq22ebggcw6zxdmu3ijmqh4ecel5vlhq"
  tenantId: "ocid1.tenancy.oc1..aaaaaaaagkbzgg6lpzrf47xzy4rjoxg4de6ncfiq2rncmjiujvy2hjgxvziq"
  authEndpoint: "https://auth.us-phoenix-1.oraclecloud.com"
  frontendEndpoint: "https://r37da9871-71b9-40ba-b0d2-0eb0d313f2e6.kiev.ad1.us-phoenix-1.oci.oracleiaas.com"
  rootCertPemPath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  clientType: service
  transactionMaxWrites: 50
  transactionMaxReads: 1000
}

authConfig {
  authorizationEnabled: false
  tenantId: ocid1.tenancy.oc1..aaaaaaaa6gqokctiy6pncv6jooomauqibkkhduaohvikdrwi6ze2n5o5v3kq
  authServiceEndpoint: "https://auth."${env.publicDomainName}
  instancePrincipalUrl: "http://localhost:8000/opc/v1/"
  defaultTrustStorePath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
}

metricsConfig {
  t2Config: {

    # The fleet name to be published for every metric
    fleet: lvv-portal.lvv-service-beta

    # For overlay we use the following endpoint
    endpointOverride: "https://telemetry-ingestion."${env.publicDomainName}
  }
}

secretServiceConfig: {
  endpoint: "https://secret-service-ce."${env.iaasDomainName}"/v1"
  tlsConfig: {
      caBundle: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  }
}
