include "prod.conf"

kaasStoreConfig: {
  storeName: "lvv_kiev_r2"
  appName: "lvv-service-dev"
  compartmentId: "ocid1.compartment.oc1..aaaaaaaacgjij2knzf3uei7kjel4zq22ebggcw6zxdmu3ijmqh4ecel5vlhq"
  tenantId: "ocid1.tenancy.oc1..aaaaaaaagkbzgg6lpzrf47xzy4rjoxg4de6ncfiq2rncmjiujvy2hjgxvziq"
  authEndpoint: "https://auth."${env.publicDomainName}
  frontendEndpoint: "https://r37da9871-71b9-40ba-b0d2-0eb0d313f2e6.kiev.ad1.us-phoenix-1.oci.oracleiaas.com"
  rootCertPemPath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  clientType: service
}