include "prod.conf"

kaasStoreConfig: {
  storeName: "lvv_kiev_r2_prod"
  appName: "lvv-service"
  compartmentId: "ocid1.compartment.oc1..aaaaaaaah5zjoyuwkiwioc5x2eg6z3x2acnflwcsgkskxojlvc47xrrnlwza"
  tenantId: "ocid1.tenancy.oc1..aaaaaaaaywhaamy7roi5jggknnfrucxsbshmvrtv23nfurmtghsgomi3afhq"
  authEndpoint: "https://auth."${env.publicDomainName}
  frontendEndpoint: "https://r37da9871-71b9-40ba-b0d2-0eb0d313f2e6.kiev.ad1.us-phoenix-1.oci.oracleiaas.com"
  rootCertPemPath: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
  clientType: service
}