<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.oracle.pic.networking.lvv.service</groupId>
    <artifactId>lvv-service-reactor-pom</artifactId>
    <version>0.1-SNAPSHOT</version>
  </parent>

  <artifactId>lvv-service-api</artifactId>
  <packaging>jar</packaging>
  <name>lvv-service-api</name>

  <properties>
    <jar.main.class>com.oracle.pic.networking.lvv.service.LvvServiceApi</jar.main.class>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <swagger-spec-temp-dir>${project.build.directory}</swagger-spec-temp-dir>
    <!-- By default build the release version of the spec file -->
    <spec-target-group>release</spec-target-group>
    <!--
        Swagger spec is defined in lvv-service-spec/specs/api.cond.yaml

        spec-conditionals-preprocessor-plugin generates ${spec-target-group}/api.yaml based on enabled group files.

        Having multiple enabled group files allows you to specify different enabled groups at different stages of your
        service, e.g. have experimental features enabled in a test environment, but only released features in production.

        For details refer to following pages -
        https://confluence.oci.oraclecorp.com/display/DEX/Swagger+Spec+Preprocessor
        https://confluence.oci.oraclecorp.com/display/DEX/Swagger+Spec+Branching+Strategy
    -->
    <spec-file>${swagger-spec-temp-dir}/${spec-target-group}/api.yaml</spec-file>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.oracle.pic.storekeeper</groupId>
      <artifactId>storekeeper-java-client</artifactId>
      <version>2.1.51</version>
      <exclusions>
        <exclusion>
          <groupId>com.oracle.oci.sdk</groupId>
          <artifactId>oci-java-sdk-common</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.oci.sdk</groupId>
      <artifactId>oci-java-sdk-common</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>core-regions</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>metrics</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.telemetry.overlay.metrics</groupId>
      <artifactId>metrics-module</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.telemetry.commons</groupId>
      <artifactId>metrics-lib</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.commons</groupId>
      <artifactId>service-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.networking.ncp</groupId>
      <artifactId>ncp-api-java-public-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.identity.authorization</groupId>
      <artifactId>sdk</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.oracle.pic.limits</groupId>
          <artifactId>compartment-quotas-sdk</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.oracle.pic.rqs.publishing.kiev</groupId>
          <artifactId>resource-publishing-kiev</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.googlecode.protobuf-java-format</groupId>
          <artifactId>protobuf-java-format</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.identity.authentication</groupId>
      <artifactId>authentication-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.identity.authorization</groupId>
      <artifactId>metrics-implementation</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.identity.authorization</groupId>
      <artifactId>jersey-2-29-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.sherlock</groupId>
      <artifactId>sherlock-collector-dropwizard</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.sherlock</groupId>
      <artifactId>sherlock-collector-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.oracle.oci.sdk</groupId>
          <artifactId>oci-java-sdk-audit</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.pegasus</groupId>
      <artifactId>pegasus-swagger-ui</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-assets</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-jersey</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-lifecycle</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-servlets</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard-bundles</groupId>
      <artifactId>dropwizard-configurable-assets-bundle</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-healthchecks</artifactId>
    </dependency>
    <dependency>
      <groupId>io.dropwizard</groupId>
      <artifactId>dropwizard-servlets</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.validation</groupId>
      <artifactId>validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-lang</groupId>
      <artifactId>commons-lang</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>2.0.7</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>2.0.7</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.mockito</groupId>
          <artifactId>mockito-core</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.vault</groupId>
      <artifactId>vault-java-sdk</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.vault</groupId>
      <artifactId>vault-user-java-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.sfw</groupId>
      <artifactId>sfw-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.prism.agent</groupId>
      <artifactId>prism-agent</artifactId>
    </dependency>
    <!-- Atlassian dependencies -->
    <dependency>
      <groupId>com.atlassian.jira</groupId>
      <artifactId>jira-rest-java-client-api</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.sun.jersey</groupId>
          <artifactId>jersey-client</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.sun.jersey</groupId>
          <artifactId>jersey-json</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.atlassian.jira</groupId>
      <artifactId>jira-rest-java-client-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.sun.jersey</groupId>
          <artifactId>jersey-client</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.sun.jersey</groupId>
          <artifactId>jersey-json</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.atlassian.jira</groupId>
      <artifactId>jira-api</artifactId>
      <exclusions>
        <exclusion>
          <groupId>com.atlassian.event</groupId>
          <artifactId>atlassian-event</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.core</groupId>
          <artifactId>atlassian-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jakarta.mail</groupId>
          <artifactId>jakarta.mail-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.antlr</groupId>
          <artifactId>antlr4-runtime</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.apache.velocity</groupId>
          <artifactId>velocity</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.annotations</groupId>
          <artifactId>atlassian-annotations</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.analytics</groupId>
          <artifactId>analytics-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.jackson</groupId>
          <artifactId>jackson-mapper-asl</artifactId>
        </exclusion>
        <exclusion>
          <groupId>dom4j</groupId>
          <artifactId>dom4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.sal</groupId>
          <artifactId>sal-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.plugins</groupId>
          <artifactId>atlassian-plugins-webfragment</artifactId>
        </exclusion>
        <exclusion>
          <groupId>jfree</groupId>
          <artifactId>jcommon</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.atlassian.plugins</groupId>
          <artifactId>atlassian-plugins-webfragment-api</artifactId>
        </exclusion>
        <exclusion>
          <groupId>opensymphony</groupId>
          <artifactId>propertyset</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.codehaus.jackson</groupId>
          <artifactId>jackson-core-asl</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.codehaus.jettison</groupId>
      <artifactId>jettison</artifactId>
    </dependency>
    <dependency>
      <groupId>com.oracle.pic.kiev</groupId>
      <artifactId>kiev-library</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>

      <plugin>
        <!-- Copy the api.yaml file to the build output directory -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.3.0</version>
        <configuration>
          <ignoredDependencies>
            <ignoredDependency>commons-lang:commons-lang</ignoredDependency>
          </ignoredDependencies>
        </configuration>
        <executions>
          <execution>
            <id>unpack</id>
            <goals>
              <goal>unpack</goal>
            </goals>
            <phase>initialize</phase>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.oracle.pic.networking.lvv.service</groupId>
                  <artifactId>lvv-service-spec</artifactId>
                  <type>jar</type>
                  <includes>${spec-target-group}/api.yaml</includes>
                  <outputDirectory>${swagger-spec-temp-dir}</outputDirectory>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
          <execution>
            <id>copy</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.oracle.pic.jipher</groupId>
                  <artifactId>jipher-jce</artifactId>
                  <!--suppress UnresolvedMavenProperty -->
                  <version>${jipher-jce-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>bc-fips</groupId>
                  <artifactId>bc-fips</artifactId>
                  <!--suppress UnresolvedMavenProperty -->
                  <version>${bouncycastle-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>bcpkix-fips</groupId>
                  <artifactId>bcpkix-fips</artifactId>
                  <!--suppress UnresolvedMavenProperty -->
                  <version>${bouncycastle-version}</version>
                  <outputDirectory>${project.build.directory}/classpath</outputDirectory>
                </artifactItem>
                <artifactItem>
                  <groupId>com.oracle.pic.prism.agent</groupId>
                  <artifactId>prism-agent</artifactId>
                  <outputDirectory>${project.build.directory}/agentpath</outputDirectory>
                </artifactItem>
              </artifactItems>
              <stripVersion>true</stripVersion>
            </configuration>
          </execution>
          <execution>
            <id>analyze-dependencies</id>
            <configuration>
              <usedDependencies>
                <!-- Used at runtime for the service explorer UI. -->
                <dependency>com.oracle.pic.pegasus:pegasus-swagger-ui</dependency>
                <dependency>io.dropwizard:dropwizard-assets</dependency>

                <!-- Used at build time for maven-surefire-plugin to have a Test Engine. -->
                <dependency>org.junit.jupiter:junit-jupiter-engine</dependency>

                <!-- Used at runtime by the Prism JCE metrics library.
                     The prism-agent is a Java agent. Agents are not included in the main (shaded) jar. It will be
                     provided at runtime by passing '-javaagent:/path/to/prism-agent.jar' to the java command line -->
                <dependency>com.oracle.pic.prism.agent:prism-agent</dependency>
              </usedDependencies>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <!-- Copies (does not filter) config resources from config to target/config -->
          <execution>
            <id>copy-config-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/config</outputDirectory>
              <resources>
                <resource>
                  <directory>config</directory>
                  <includes>
                    <include>*.conf</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-scripts-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/scripts</outputDirectory>
              <resources>
                <resource>
                  <directory>scripts</directory>
                  <includes>
                    <include>*</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-docker-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/docker</outputDirectory>
              <resources>
                <resource>
                  <directory>docker</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
          <execution>
            <id>copy-environment-config-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/environment-config</outputDirectory>
              <resources>
                <resource>
                  <directory>environment-config</directory>
                  <includes>
                    <include>*.env</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.oracle.pic.commons.maven</groupId>
        <artifactId>oracle-swagger-maven-plugin</artifactId>
        <version>1.5.75</version>
        <executions>
          <execution>
            <id>generateModelsAndAbstractClasses</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <basePackage>com.oracle.pic.networking.lvv.service</basePackage>
              <language>oracle-java-jaxrs-service</language>
              <specPath>${spec-file}</specPath>
              <generateClient>false</generateClient>
              <generateAbstractResources>true</generateAbstractResources>
              <additionalProperties>
                <sortParamsByRequiredFlag>false</sortParamsByRequiredFlag>
              </additionalProperties>
            </configuration>
          </execution>
          <execution>
            <id>generateSpecs</id>
            <goals>
              <goal>generateSpecs</goal>
            </goals>
            <configuration>
              <yamlSpecInputPath>${spec-file}</yamlSpecInputPath>
              <!-- The file will be reachable at http://host:port/spec/api.json -->
              <enableJson>true</enableJson>
              <!-- The file will be reachable at http://host:port/spec/api.yaml -->
              <enableYaml>true</enableYaml>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.oracle.pic.commons.maven</groupId>
        <artifactId>oracle-typesafe-config-validator-plugin</artifactId>
        <version>2.0.16</version>
        <executions>
          <execution>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <configsSet>
                <directory>${basedir}/config</directory>
              </configsSet>
              <resolvedConfigDirectory>${project.build.directory}/resolved-config</resolvedConfigDirectory>
              <unresolvedSubstitutions>
                <unresolvedSubstitution>env.availabilityDomain</unresolvedSubstitution>
                <unresolvedSubstitution>env.region</unresolvedSubstitution>
                <unresolvedSubstitution>env.adNumber</unresolvedSubstitution>
                <unresolvedSubstitution>env.regionInternalName</unresolvedSubstitution>
                <unresolvedSubstitution>env.dbTnsName</unresolvedSubstitution>
                <unresolvedSubstitution>env.publicDomainName</unresolvedSubstitution>
                <unresolvedSubstitution>env.iaasDomainName</unresolvedSubstitution>
              </unresolvedSubstitutions>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Java code coverage -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.10</version>
        <configuration>
          <outputDirectory>${project.build.directory}/jacoco-reports</outputDirectory>
          <excludes>
            <!--
              Exclusions for code coverage
              Excluding auto-generated source, main classes, configs and constants.
              For more details, please see https://www.eclemma.org/jacoco/trunk/doc/report-mojo.html#excludes
            -->
            <!-- auto-generated -->
            <exclude>com/oracle/pic/networking/lvv/service/api/**/*</exclude>
            <exclude>com/oracle/pic/networking/lvv/service/model/**/*</exclude>
            <!-- config -->
            <exclude>com/oracle/pic/networking/lvv/service/config/**/*</exclude>
            <!-- constants -->
            <exclude>com/oracle/pic/networking/lvv/service/auth/AuthVerbs.class</exclude>
            <!-- ignore main classes -->
            <exclude>com/oracle/pic/networking/lvv/service/LvvServiceApi*.class</exclude>
            <!-- did nothing, only for local testing purpose -->
            <exclude>com/oracle/pic/networking/lvv/service/auth/PassThruAuthHelper.class</exclude>
            <!-- ignore common for testing -->
            <exclude>com/oracle/pic/networking/lvv/service/common/**/*</exclude>
            <!-- ignore identity for testing -->
            <exclude>com/oracle/pic/networking/lvv/service/identity/**/*</exclude>
            <!-- ignore MockNcpClients for testing -->
            <exclude>com/oracle/pic/networking/lvv/service/dependencies/ncp/Mock*.class</exclude>
            <!-- ignore Kiev Helper class for testing -->
            <exclude>com/oracle/pic/networking/lvv/service/kiev/DataStoreProvider.class</exclude>
            <exclude>com/oracle/pic/networking/lvv/service/kiev/KievHashBucketProvider.class</exclude>
            <!-- ignore helper class for testing -->
            <exclude>com/oracle/pic/networking/lvv/service/etag/*</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>default-prepare-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>default-report</id>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
          <execution>
            <id>default-check</id>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule
                  implementation="org.jacoco.maven.RuleConfiguration">
                  <element>BUNDLE</element>
                  <limits>
                    <limit
                      implementation="org.jacoco.report.check.Limit">
                      <counter>INSTRUCTION</counter>
                      <value>COVEREDRATIO</value>
                      <!-- Tweak this as you gain coverage -->
                      <!-- Will fast followup to make this 0.8 -->
                      <minimum>0.70</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- maven-shade-plugin:
           When instantiating a JCE provider's implementation (class) of a Cipher, KeyAgreement, KeyGenerator, MAC or
           SecretKey factory, the JCA framework determines the provider's codebase (JAR file) and verifies its signature.
           In this way, the JCA authenticates the provider and ensures that only providers signed by a trusted entity
           can be plugged into the JCA. Consequently, these classes cannot be extracted from their original JARs,
           such as the jipher-jce and bc-fips JARs, and included in an application's Uber JAR.
           Instead the original signed JARs must be available to the classloader by placing them in the classpath
           There is corresponding config in the maven-dependency-plugin, to copy the signed JARs into the classpath,
           and actions in the dockerfile to embed the signed JARs in the docker image. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.4.0</version>
        <configuration>
          <!-- We shouldn't need the Dependency Reduced Pom.  Don't change it. -->
          <createDependencyReducedPom>false</createDependencyReducedPom>
          <filters>
            <filter>
              <artifact>*:*</artifact>
              <excludes>
                <exclude>META-INF/*.SF</exclude>
                <exclude>META-INF/*.DSA</exclude>
                <exclude>META-INF/*.RSA</exclude>
                <exclude>org/bouncycastle</exclude>
                <exclude>org/bouncycastle/**/*</exclude>
              </excludes>
            </filter>
          </filters>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <manifestEntries>
                    <Main-Class>${jar.main.class}</Main-Class>
                    <Class-Path>classpath/jipher-jce.jar classpath/bc-fips.jar classpath/bcpkix-fips.jar</Class-Path>
                  </manifestEntries>
                </transformer>
              </transformers>
              <artifactSet>
                <excludes>
                  <exclude>com.oracle.pic.prism.agent:prism-agent</exclude>
                  <exclude>com.oracle.pic.jipher:jipher-jce</exclude>
                  <exclude>bc-fips:bc-fips</exclude>
                  <exclude>bcpkix-fips:bcpkix-fips</exclude>
                  <exclude>org.bouncycastle:bcprov-jdk15on</exclude>
                  <exclude>org.bouncycastle:bcpkix-jdk15on</exclude>
                </excludes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
