#!/bin/bash
exec 2>&1

# =============================================================================
# Launch Chainsaw2
# =============================================================================
exec chainsaw2 \
    --compartment="ocid1.compartment.oc1..aaaaaaaa2c63ndkfikkpelwaxhqkdmbi2r52tcy6gcm47fmv24b65dprtqoq" \
    --namespace="lvv-service-canary"

