include "dev"

logdir: ./abandoned/logs

locationOverride {
     region: "dev"
     availabilityDomain: "dev-1"
}

server {
  requestLog {
    appenders: [{
      type: console
      timeZone: UTC
      threshold: ALL
      target: stdout
      # Default pattern found at:
      # https://github.com/dropwizard/dropwizard/blob/master/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/layout/LogbackAccessRequestLayout.java
      logFormat: "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z,UTC}] \"%responseHeader{opc-request-id}\" \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D"
    }]
  }
}

logging {
  appenders += {
      type: console
      timeZone: UTC
      threshold: DEBUG
      target: stdout
      logFormat: "%-5level %date{ISO8601, UTC} %mdc{opc-request-id} [%thread] %logger: %message%n"
    }
}

metricsConfig {
  locationOverride {
    availabilityDomain=DEV_1
    region=DEV
  }
  t2Config: null
}
