include "prod"

secretServiceConfig: {
  endpoint: "https://secret-service-ce."${env.iaasDomainName}"/v1"
  tlsConfig: {
    caBundle: "/etc/oci-pki/ca-bundle.pem"
  }
}

metricsConfig {
  t2Config: {
    # For overlay we use the following endpoint
    endpointOverride: "https://telemetry-ingestion."${env.publicDomainName}
  }
}
